version: '3.8'

services:
  app:
    build: .
    container_name: vinyl-backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "4242:4242"
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: vinyl-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: disc_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: vinyl-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data:

