spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/disc_shop?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 600000
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.trikynguci.springbootvinylecommercebackend.model
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
vietqr:
  clientId: ${VIETQR_CLIENT_ID}
  apiKey: ${VIETQR_API_KEY}

# Payment Provider Configuration
vnpay:
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paygate/vpc.htm}
  returnUrl: ${VNPAY_RETURN_URL:http://localhost:4242/api/v1/payments/webhook/vnpay}
  tmnCode: ${VNPAY_TMN_CODE}
  hashSecret: ${VNPAY_HASH_SECRET}

momo:
  endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
  returnUrl: ${MOMO_RETURN_URL:http://localhost:4242/api/v1/payments/webhook/momo}
  partnerCode: ${MOMO_PARTNER_CODE}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}

zalopay:
  endpoint: ${ZALOPAY_ENDPOINT:https://sb-openapi.zalopay.vn/v2/create}
  returnUrl: ${ZALOPAY_RETURN_URL:http://localhost:4242/api/v1/payments/webhook/zalopay}
  appId: ${ZALOPAY_APP_ID}
  key1: ${ZALOPAY_KEY1}
  key2: ${ZALOPAY_KEY2}

server:
  port: 4242

