spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disc_shop?createDatabaseIfNotExist=true
    username: root
    password: 332003
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: 24550024@gm.uit.edu.vn
    password: ekrdwaycukhnpnka
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: redis
  data:
    redis:
      host: redis-19977.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 19977
      timeout: 600000
      password: a1o7fdtainqkwHAlt1Mg1J3zdzpDrIhj
      username: default
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.trikynguci.springbootvinylecommercebackend.model
application:
  security:
    jwt:
      secret-key: 1sugz2yXUwLXNB6Lgtl0cLr5aXLL/sVPA3MjsGBuHFA=
      expiration: 86400000
      refresh-token:
        expiration: 604800000
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
vietqr:
  clientId: c89a7308-c86a-4ae7-9fb5-414993c7fca3
  apiKey: 76c40c1e-c595-4662-a777-0260ec3f1cfb
server:
  port: 4242
