spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/disc_shop?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 600000
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.trikynguci.springbootvinylecommercebackend.model
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
vietqr:
  clientId: ${VIETQR_CLIENT_ID}
  apiKey: ${VIETQR_API_KEY}
server:
  port: 4242
