spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disc_shop?createDatabaseIfNotExist=true
    username: root
    password: 332003
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.trikynguci.springbootvinylecommercebackend.model
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 86400000
      refresh-token:
        expiration: 604800000
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
vietqr:
  clientId: c89a7308-c86a-4ae7-9fb5-414993c7fca3
  apiKey: 76c40c1e-c595-4662-a777-0260ec3f1cfb
server:
  port: 4242