spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disc_shop?createDatabaseIfNotExist=true
    username: root
    password: 332003
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.trikynguci.springbootvinylecommercebackend.model
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 86400000
      refresh-token:
        expiration: 604800000
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/Payment/Error.html?code=03
    tmnCode: HZVR8FCM
    secretKey: DQZS8BAYS9SOKSQMYUMELQ428NX43BOG
    returnUrl: http://localhost:4242/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
server:
  port: 4242